//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futbolcu
    {
        public int id { get; set; }
        public string takimid { get; set; }
        public string isim { get; set; }
    }
}
