//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int id { get; set; }
        public string isim { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<int> puan { get; set; }
        public Nullable<int> seviye { get; set; }
        public Nullable<int> yas { get; set; }
        public Nullable<int> mail { get; set; }
        public Nullable<System.DateTime> ensonoynamatarihi { get; set; }
        public byte[] gecicilokasyon { get; set; }
    }
}
