//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int id { get; set; }
        public int kullaniciid { get; set; }
        public int logoid { get; set; }
        public Nullable<bool> bildimi { get; set; }
        public Nullable<int> kacsaniyede { get; set; }
    }
}
