//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logo
    {
        public int id { get; set; }
        public int markaid { get; set; }
        public string resim { get; set; }
        public string renk1 { get; set; }
        public string renk2 { get; set; }
        public string renk3 { get; set; }
        public string renk4 { get; set; }
        public string renk5 { get; set; }
        public string resim2 { get; set; }
        public Nullable<int> seviye { get; set; }
    }
}
