//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omermobil_dbEntities1 : DbContext
    {
        public omermobil_dbEntities1()
            : base("name=omermobil_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dukkanlar> Dukkanlars { get; set; }
        public DbSet<Futbolcu> Futbolcus { get; set; }
        public DbSet<Kullanici> Kullanicis { get; set; }
        public DbSet<Loglar> Loglars { get; set; }
        public DbSet<Logo> Logoes { get; set; }
        public DbSet<Marka> Markas { get; set; }
        public DbSet<Reklam> Reklams { get; set; }
        public DbSet<MarkaLogo> MarkaLogoes { get; set; }
        public DbSet<MarkaReklam> MarkaReklams { get; set; }
    }
}
