//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklam
    {
        public int id { get; set; }
        public Nullable<int> markaid { get; set; }
        public string resim { get; set; }
        public string aciklama { get; set; }
        public string link { get; set; }
        public Nullable<int> goruntulenmesayisi { get; set; }
    }
}
